name: Renovate

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json"
      - ".github/workflows/renovate.yml"

permissions: {}

jobs:
  renovate:
    permissions:
      contents: read
    uses: projectbluefin/actions/.github/workflows/reusable-renovate.yml@52c87987ba73e7359b25e2e8010fb1de7b619bd9 # v1
    secrets:
      renovate_token: ${{ secrets.RENOVATE_TOKEN }}
