name: Renovate

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json"
      - ".github/workflows/renovate.yml"

permissions: {}

jobs:
  renovate:
    permissions:
      contents: read
    uses: projectbluefin/actions/.github/workflows/reusable-renovate.yml@a52da5670b9337598cbc80c4d6a9a7b21e770aec # v1
    secrets:
      renovate_token: ${{ secrets.RENOVATE_TOKEN }}
