name: Validate Renovate Config

on:
  pull_request:
    paths:
      - ".github/renovate.json"
      - ".github/workflows/renovate.yml"
      - ".github/workflows/validate-renovate.yml"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json"
      - ".github/workflows/renovate.yml"
      - ".github/workflows/validate-renovate.yml"

permissions:
  {}

jobs:
  validate:
    permissions:
      contents: read
    uses: projectbluefin/actions/.github/workflows/reusable-validate-renovate.yml@58466c868ec3f0eb2d0daf77bf90f61afcf821ee # v1
